version: "3"
services:
  postgres:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  prisma:
    image: prismagraphql/prisma:1.31
    restart: "no"
    depends_on:
      - postgres
    ports:
      - "4466:4466"
    environment:
      JAVA_OPTS: "-Xmx1g"
      PRISMA_CONFIG: |
        port: 4466
        # prototype: true
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  # api:
  #   build: .
  #   ports:
  #     - "4001:4001"
  #   restart: "no"
  #   env_file:
  #     - .env
  #   environment:
  #     PORT: 4001
  #     PRISMA_ENDPOINT: http://prisma:4466
volumes:
  postgres:
