# This deploys both the Prisma Server and an Attached Postgres
environments:
  dev: {}
  staging: {}
  production: {}

releases:
  - name: spotfire-prisma
    namespace: spotfire
    labels:
      layer: data
    chart: stable/prisma
    version: 1.2.1
    values:
    - ../values/prisma/values.yaml
    secrets:
    - ../values/prisma/secrets.yaml
