apiVersion: v1
kind: ConfigMap
metadata:
  name: auth0-config
  labels:
    app: {{ .Chart.Name }}
    chart: {{.Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  AUTH0_DOMAIN: {{ .Values.auth0.domain | quote }}
  AUTH0_CLIENT_ID: {{ .Values.auth0.client_id | quote }}
