apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  labels:
    app: {{ .Chart.Name }}
    chart: {{.Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access_key_id | quote }}
  AWS_S3_EXTRACT_BUCKET_NAME: {{ .Values.aws.s3_extract_bucket_name | quote }}
