apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-config
  labels:
    app: {{ .Chart.Name }}
    chart: {{.Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PRISMA_ENDPOINT: {{ .Values.prisma.endpoint | quote }}
